//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPJECT4NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes_SM1
    {
        public string date { get; set; }
        public string day { get; set; }
        public string Class_Id { get; set; }
        public string Type { get; set; }
        public Nullable<double> Capacity { get; set; }
        public Nullable<double> C08_09 { get; set; }
        public Nullable<double> C09_10 { get; set; }
        public Nullable<double> C10_11 { get; set; }
        public Nullable<double> C11_12 { get; set; }
        public Nullable<double> C12_13 { get; set; }
        public Nullable<double> C13_14 { get; set; }
        public Nullable<double> C14_15 { get; set; }
        public Nullable<double> C15_16 { get; set; }
        public Nullable<double> C16_17 { get; set; }
        public Nullable<double> C17_18 { get; set; }
        public Nullable<double> C18_19 { get; set; }
        public Nullable<double> C19_20 { get; set; }
        public Nullable<double> C20_21 { get; set; }
        public Nullable<double> holiday { get; set; }
        public string record { get; set; }
    }
}
