//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPJECT4NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_detail
    {
        public int Course_id { get; set; }
        public int Course_Serial { get; set; }
        public int Group_num { get; set; }
        public int Year { get; set; }
        public string Prev_course { get; set; }
        public string Teacher { get; set; }
        public string Day { get; set; }
        public Nullable<int> Start_time { get; set; }
        public Nullable<int> End_time { get; set; }
        public Nullable<int> Class_number { get; set; }
        public Nullable<int> Student_Count { get; set; }
        public Nullable<int> Capacity { get; set; }
    }
}
