//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPJECT4NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class cours
    {
        public int Course_id { get; set; }
        public string Course_name { get; set; }
        public double Nakaz { get; set; }
        public int Year { get; set; }
        public string Semester { get; set; }
        public Nullable<int> Blocking_Cource { get; set; }
    }
}
