//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPJECT4NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ID { get; set; }
        public int Course_ID { get; set; }
        public int Start_Time { get; set; }
        public int End_Time { get; set; }
        public string Class { get; set; }
        public string Superviser1_ID { get; set; }
        public string Superviser2_ID { get; set; }
        public int Student_Enrolled { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Due_in { get; set; }
    }
}
