//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPJECT4NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecture_Course
    {
        public int Course_ID { get; set; }
        public int Course_Serial { get; set; }
        public int Course_type { get; set; }
        public string Teacher { get; set; }
        public string Date { get; set; }
        public int Start_time { get; set; }
        public int End_time { get; set; }
        public string Class_number { get; set; }
        public int Student_Count { get; set; }
    }
}
