//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPJECT4NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public string ID { get; set; }
        public string F_name { get; set; }
        public string L_name { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Permission { get; set; }
    }
}
