//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPJECT4NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scholarship
    {
        public string Scholership_ID { get; set; }
        public string Scholership_Name { get; set; }
        public int Grant_Amount_shekel_ { get; set; }
        public string Intended_for { get; set; }
        public int Duration_years_ { get; set; }
        public Nullable<int> Volunteer_hours { get; set; }
    }
}
