//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPJECT4NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Courses
    {
        public string stud_Id { get; set; }
        public double course_id { get; set; }
        public Nullable<double> grade_a { get; set; }
        public Nullable<double> grade_b { get; set; }
        public Nullable<double> grade_c { get; set; }
        public Nullable<double> quiz1 { get; set; }
        public Nullable<double> quiz2 { get; set; }
        public Nullable<int> final_grade { get; set; }
        public int Type { get; set; }
        public Nullable<int> course_serial { get; set; }
        public Nullable<int> Exam1_ID { get; set; }
        public Nullable<int> Exam2_ID { get; set; }
        public Nullable<int> Exam3_ID { get; set; }
    }
}
