//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPJECT4NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_special_Exam
    {
        public string ID { get; set; }
        public int Course_Serial { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
    }



}
