//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPJECT4NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public string ID { get; set; }
        public string Department { get; set; }
        public byte Year { get; set; }
        public Nullable<double> Average { get; set; }
        public bool ExtraTime { get; set; }
        public bool Laptop { get; set; }
        public bool FormulaSheet { get; set; }
    }
}
